phases:
- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - template: .vsts-ci-steps.yml

- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - template: .vsts-ci-steps.yml

- phase: Windows
  queue: Hosted VS2017
  steps:
  - template: .vsts-ci-steps.yml

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      nobuild: true
    displayName: Pack

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: Artifacts
    displayName: Publish Artifacts