phases:
- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - template: .vsts-ci-steps.yml

  - task: MSBuild@1
    inputs:
      solution: src/Xamarin.MSBuild.Tooling.Tests/Xamarin.MSBuild.Tooling.NetFXTests.csproj
      msbuildArguments: '/restore /t:Test'
    continueOnError: true
    displayName: Run Manual MSBuild.Tooling Tests

- phase: Windows
  queue: Hosted VS2017
  steps:
  - template: .vsts-ci-steps.yml

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      nobuild: true
    displayName: Pack

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: Artifacts
    displayName: Publish Artifacts