phases:
- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - template: .vsts-ci-steps.yml

- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - template: .vsts-ci-steps.yml

- phase: Windows
  queue: Hosted VS2017
  steps:
  - template: .vsts-ci-steps.yml

  - script: |
      dotnet pack
    displayName: Pack Libraries

  - task: MSBuild@1
    inputs:
      solution: src/Xamarin.MSBuild.Tool/Xamarin.MSBuild.Tool.csproj
      msbuildArguments: '/restore /t:Build'
    displayName: Pack Tools

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: Artifacts
      PathtoPublish: _artifacts
    displayName: Publish Artifacts