steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: 2.1.402
  displayName: Install .NET Core

# This script runs both via bash (macOS/Linux) and cmd (Windows).
# Keep it both valid bash and batch or break it out conditionally.
- script: |
    echo System Environment
    set
    echo .NET Core Info
    dotnet --info
  displayName: Dump Environment

- script: |
    rm msbuild.rsp
  displayName: Remove MSBuild autoresponse file

- script: |
    dotnet restore
  displayName: Restore

- script: |
    dotnet build --no-restore -v detailed mirepoix.proj
  displayName: Build

- script: |
    dotnet msbuild mirepoix.proj /t:TestAll
  continueOnError: true
  displayName: Run Unit Tests