phases:
- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - template: .vsts-ci-steps.yml

- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - template: .vsts-ci-steps.yml

- phase: Windows
  queue: Hosted VS2017
  steps:
  - template: .vsts-ci-steps.yml

  - task: DotNetCoreCLI@2
    inputs:
      command: pack
      nobuild: true
    displayName: Pack Libraries

  - task: MSBuild@1
    inputs:
      solution: src/Xamarin.MSBuild.Tool/Xamarin.MSBuild.Tool.csproj
      msbuildArguments: '/restore /t:Pack'
    displayName: Pack Tools

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: Artifacts
    displayName: Publish Artifacts